name: Import Competition Tasks

on:
  workflow_dispatch

env:
  SR_YEAR: 2025

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: srobo/recurring-tasks
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r scripts/requirements.txt
    - name: Setup token
      run: |
        echo -n "${{ secrets.GITHUB_TOKEN }}" > .github-auth
    - name: Run import
      run: |
        python scripts/import.py --area-owners --task-list --github-repo "${{ github.repository }}" --cache import_cache.json comp/main $SR_YEAR
    - name: Save import cache
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: import_cache
        path: import_cache.json
